### ISSUE TITLE
Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by weradsaoud** [Sxxov/windows-ss#1]
Hi ...
When module is required:
`const { getMonitorInfos } = require('windows-ss');`
An error occured:
App threw an error during load
Error: The specified procedure could not be found.
\\?\D:\werad\WrknzrDsktp\Workganizer_v1_POM_windows\node_modules\windows-ss\dist\native\win32\x64\12.13.0\edge_coreclr.node       
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\werad\WrknzrDsktp\Workganizer_v1_POM_windows\node_modules\windows-ss\dist\index.js:104:10)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\werad\WrknzrDsktp\Workganizer_v1_POM_windows\public\electron.js:14:29)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)

**Comment by sxxov** [comment]
this seems to be an issue related to electron, can you check if `windows-ss\dist\native\win32\x64\12.13.0\edge_coreclr.node` is included in your asar bundle?

EDIT: try setting `process.env.EDGE_DEBUG = 1` & posting another stack trace, that may give more info on edge's instantiation

**Comment by sxxov** [comment]
going to close this as it doesn't seem like it's a problem with the library, hope you've found a solution to your problem.
